-- ============================================================
-- Shared Memory Project — Supabase 확장 SQL (공동 기억 고도화)
-- Supabase 대시보드 → SQL Editor 에 붙여넣고 한 번 실행하세요.
-- · 여러 번 실행해도 안전하도록 작성했습니다 (if not exists / drop if exists).
-- · 기존 행은 수정하지 않습니다. 새 컬럼은 모두 비어 있어도(null) 되는 컬럼입니다.
-- · 이 SQL을 실행하기 전에도 사이트는 동작합니다 (확장 항목만 저장되지 않음).
-- ============================================================

-- 1) 공동 표현 확장 컬럼 --------------------------------------
alter table public.shared_expressions
  add column if not exists expression_style  text,     -- STEP 2 표현 방식: fact | perspective | shared | future
  add column if not exists selected_concepts text[],   -- STEP 1 선택한 핵심 요소(화면 표시 이름)
  add column if not exists reason_tags       text[],   -- STEP 4 이유 항목 코드
  add column if not exists before_content    text;     -- 탐구 전 한 문장 (BEFORE)

-- 2) 입력값 제한 (NOT VALID: 기존 행은 검사하지 않고, 새로 들어오는 행만 검사) --
do $$ begin
  alter table public.shared_expressions add constraint shared_expressions_style_chk
    check (expression_style is null or expression_style in ('fact', 'perspective', 'shared', 'future')) not valid;
exception when duplicate_object then null; end $$;

do $$ begin
  alter table public.shared_expressions add constraint shared_expressions_content_len_chk
    check (char_length(content) between 1 and 1000) not valid;
exception when duplicate_object then null; end $$;

do $$ begin
  alter table public.shared_expressions add constraint shared_expressions_author_len_chk
    check (author_name is null or char_length(author_name) <= 40) not valid;
exception when duplicate_object then null; end $$;

do $$ begin
  alter table public.shared_expressions add constraint shared_expressions_reason_len_chk
    check (reason is null or char_length(reason) <= 1000) not valid;
exception when duplicate_object then null; end $$;

do $$ begin
  alter table public.shared_expressions add constraint shared_expressions_before_len_chk
    check (before_content is null or char_length(before_content) <= 500) not valid;
exception when duplicate_object then null; end $$;

do $$ begin
  alter table public.shared_expressions add constraint shared_expressions_arrays_chk
    check (coalesce(cardinality(selected_concepts), 0) <= 20 and coalesce(cardinality(reason_tags), 0) <= 10) not valid;
exception when duplicate_object then null; end $$;

create index if not exists shared_expressions_event_created_idx
  on public.shared_expressions (event_key, created_at desc);

-- 3) 공감 테이블 ------------------------------------------------
create table if not exists public.expression_empathy (
  id            bigint generated by default as identity primary key,
  expression_id bigint not null references public.shared_expressions (id) on delete cascade,
  voter_key     text   not null check (char_length(voter_key) between 8 and 64),
  created_at    timestamptz not null default now(),
  unique (expression_id, voter_key)          -- 같은 브라우저의 중복 공감 방지
);

create index if not exists expression_empathy_expression_idx
  on public.expression_empathy (expression_id);

alter table public.expression_empathy enable row level security;

-- 누구나 공감을 "등록"만 할 수 있습니다. 조회(select) 정책은 만들지 않아
-- voter_key 목록은 외부에서 읽을 수 없고, 집계는 아래 함수로만 제공합니다.
drop policy if exists "공감 등록 허용" on public.expression_empathy;
create policy "공감 등록 허용" on public.expression_empathy
  for insert to anon, authenticated
  with check (true);

-- 4) 사건별 공감 수 집계 함수 (RPC) ----------------------------
create or replace function public.empathy_counts(p_event_key text)
returns table (expression_id bigint, empathy_count bigint)
language sql
stable
security definer
set search_path = public
as $$
  select e.expression_id, count(*)::bigint as empathy_count
  from public.expression_empathy e
  join public.shared_expressions s on s.id = e.expression_id
  where s.event_key = p_event_key
  group by e.expression_id;
$$;

revoke all on function public.empathy_counts(text) from public;
grant execute on function public.empathy_counts(text) to anon, authenticated;

-- 5) API 스키마 캐시 새로고침 (새 컬럼·함수를 바로 인식하도록) --
notify pgrst, 'reload schema';
